= Pijul Bootstrap

This is a quick way to get started with https://pijul.org[Pijul].  Pijul is a **much better** version control system than `git`, but is a bit painful to initially install, because it depends on either itself or rust+cargo+nix.

Instead, this repo provides `pijul`` as:

- a pre-compiled as a binary for amd64 linux, which only needs some commonly available distro libraries
- a Docker Linux container image tarball, which you can download, import, and run (or use as a base image to extend) with no further dependencies (except docker/podman)
- A simple `pij` script that runs the docker image provided above (once it has been manually installed - a docker upload will come soon, meaning no manual installation other than the script itself).

== Binary executable installation

1. Download the latest pijul-$VERSION-$ARCH release executable and install it **(as root)** to /usr/local/bin (set VERSION and ARCH to match what you downloaded, of course):
+
[source,shell]
----
VERSION=1.0.0-alpha
ARCH=x86_64
install pijul-$ARCH-$VERSION /usr/local/bin/pijul
----

2. Install the dependencies.
+
For debian-likes (Debian, Ubuntu, Devuan), this command is:
[source,shell]
----
RUN apt-get update && apt-get install -y libsodium23 libssl3
----

3. Run `pijul` as usual


== Docker image

The docker image can be downloaded from releases, and used as follows  (again, set VERSION and ARCH to match what you downloaded, of course):

1. Import the docker save image:
+
[source,shell]
----
VERSION=1.0.0-alpha
ARCH=x86_64
gunzp pijul-serve-${ARCH}-${VERSION}.tar.gz
docker import pijul-serve-${ARCH}-${VERSION}.tar
----

3. Tag the version as the latest one:
+
[source,shell]
----
docker tag pijul-serve:${ARCH}-${VERSION} pijul-serve:latest
----

4. Run `pijul` using docker
+
You need to map the directory that you want to work in to /workspace, and also be sure to run it as your current user and group id, so that any files are created as you.
+
[source,shell]
----
docker run -u `id -u`:`id -g` -v $(pwd):/workspace -ti pijul-serve
----
+
See below on a script that simplifies this step.

== `pij` wrapper for docker

1. Download and install the `bin/pij` script **(as root)**:
+
[source,shell]
----
install pij /usr/local/bin
----

2. Run `pij` instead of the more complex `docker run` command given above.  They're essentially the same.

3. From now on, you can use `pij` per the documentation for `pijul` on the official website.

== Contributing

- Please fork the code and submit a PR for any improvements.  In particular, the following improvements are welcome:

  + Making the rust build fully static
  + Library installation instructions for distros other than debian-likes.
